artifacts_root: artifacts

data_ingestion:
  root_directory: artifacts/data_ingestion
  source_url: https://github.com/Aditya0135/Datasets/raw/refs/heads/main/BerlinHousingData.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir:  artifacts/data_ingestion

data_validation:
  root_directory: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/real_estate_listings_clean.csv
  STATUS_FILE: artifacts/data_validation/status.txt

  data_transformation:
    root_directory: artifacts/data_transformation
    data_path: artifacts/data_ingestion/real_estate_listings_clean.csv
    test_size: 0.2
    random_state: 42

    features:
      - area
      - rooms
      - heating
      - energy
      - zipcode

    numeric_features:
      - area
      - rooms

    categorical_features:
      - heating
      - energy
      - zipcode